# Generated by Django 3.0.5 on 2020-05-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200424_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
