# Generated by Django 3.0.5 on 2020-05-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200501_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
