# Generated by Django 3.0.5 on 2020-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200503_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
