# Generated by Django 3.0.5 on 2020-05-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shoppinglistitem_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
