# Generated by Django 3.0.5 on 2020-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200524_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
