# Generated by Django 3.0.5 on 2020-05-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shoppinglist_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='company_id',
            new_name='company',
        ),
    ]
